# Generated by Django 3.1.7 on 2021-05-18 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rfidLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfif', models.CharField(max_length=30)),
                ('date', models.DateTimeField(verbose_name='data registro')),
            ],
        ),
    ]
