# Generated by Django 3.1.7 on 2021-05-19 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rfid', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rfidlog',
            old_name='rfif',
            new_name='rfid',
        ),
    ]
