# Generated by Django 3.1.7 on 2021-05-19 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rfid', '0003_auto_20210518_2145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dispositivos',
            old_name='rfid',
            new_name='nodeId',
        ),
    ]
