# Generated by Django 3.1.2 on 2021-05-24 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rfid', '0004_auto_20210518_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='rfidUsuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('rfid', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='rfidlogs',
            name='rfid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rfid.rfidusuarios'),
        ),
    ]
