# Generated by Django 3.1.2 on 2021-05-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfid', '0006_auto_20210524_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfidusuarios',
            name='email',
            field=models.EmailField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
