# Generated by Django 3.1.2 on 2021-05-24 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rfid', '0009_auto_20210524_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfidusuarios',
            name='rfid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rfid.rfidlogs'),
        ),
    ]
