# Generated by Django 3.1.2 on 2021-05-24 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfid', '0012_auto_20210524_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfidusuarios',
            name='rfid',
            field=models.CharField(max_length=30),
        ),
    ]
